### PR TITLE
Restructure section props

### PR DESCRIPTION
**Pull request by lmestel**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/base@3.0.0-canary.1523.6422.0
  npm install @kickstartds/blog@3.0.0-canary.1523.6422.0
  npm install @kickstartds/core@3.0.0-canary.1523.6422.0
  npm install @kickstartds/form@3.0.0-canary.1523.6422.0
  npm install @kickstartds/bundler@3.0.0-canary.1523.6422.0
  # or 
  yarn add @kickstartds/base@3.0.0-canary.1523.6422.0
  yarn add @kickstartds/blog@3.0.0-canary.1523.6422.0
  yarn add @kickstartds/core@3.0.0-canary.1523.6422.0
  yarn add @kickstartds/form@3.0.0-canary.1523.6422.0
  yarn add @kickstartds/bundler@3.0.0-canary.1523.6422.0
  ```
</details>

## Breaking Changes

* Prop `headline.align` is moved to `headline.textAlign`
* Prop `headlineWidth` is moved to `headline.width`
* Prop `headlineAlign` is moved to `headline.align`
* Prop `contentWidth` is moved to `content.width`
* Prop `contentAlign` is moved to `content.align`
* Prop `gutter` is moved to `content.gutter`
* Prop `mode` is moved to `content.mode`

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0-next.10`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-next.10), [`@kickstartds/blog@3.0.0-next.9`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-next.9), [`@kickstartds/bundler@3.0.0-next.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0-next.2), [`@kickstartds/core@3.0.0-next.7`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0-next.7), [`@kickstartds/form@3.0.0-next.9`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-next.9) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0), [`@kickstartds/blog@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0), [`@kickstartds/bundler@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0), [`@kickstartds/core@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0), [`@kickstartds/form@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0), [`@kickstartds/style-dictionary@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%403.0.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.0), [`@kickstartds/blog@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.0), [`@kickstartds/bundler@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.0), [`@kickstartds/core@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.0), [`@kickstartds/form@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Pull request merged**
