### PR TITLE
Fix `Select Field` schema: `icon` property set to `object`, should be `string`

### PR DESCRIPTION
**Pull request by julrich**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/form@2.2.2-canary.1573.6569.0
  # or 
  yarn add @kickstartds/form@2.2.2-canary.1573.6569.0
  ```
</details>

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/form@2.2.3-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.2.3-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.0), [`@kickstartds/blog@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.0), [`@kickstartds/form@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@2.3.0-beta.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.1), [`@kickstartds/blog@2.3.0-beta.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.1), [`@kickstartds/form@2.3.0-beta.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.1) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.2), [`@kickstartds/blog@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.2), [`@kickstartds/core@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%402.3.0-beta.0), [`@kickstartds/form@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.2), [`@kickstartds/style-dictionary@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%402.3.0-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0), [`@kickstartds/blog@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0), [`@kickstartds/bundler@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0), [`@kickstartds/core@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0), [`@kickstartds/form@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0), [`@kickstartds/style-dictionary@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%403.0.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.0), [`@kickstartds/blog@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.0), [`@kickstartds/bundler@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.0), [`@kickstartds/core@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.0), [`@kickstartds/form@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Pull request merged**
