### PR TITLE
Reactivate storybook component-tokens addon

### PR DESCRIPTION
**Pull request by lmestel**
TODOs

- [x] Wait for the major release in https://github.com/kickstartDS/storybook-addon-component-tokens/pull/18

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/base@3.0.0-canary.1405.6438.0
  npm install @kickstartds/blog@3.0.0-canary.1405.6438.0
  npm install @kickstartds/core@3.0.0-canary.1405.6438.0
  npm install @kickstartds/form@3.0.0-canary.1405.6438.0
  npm install @kickstartds/bundler@3.0.0-canary.1405.6438.0
  npm install @kickstartds/style-dictionary@3.0.0-canary.1405.6438.0
  # or 
  yarn add @kickstartds/base@3.0.0-canary.1405.6438.0
  yarn add @kickstartds/blog@3.0.0-canary.1405.6438.0
  yarn add @kickstartds/core@3.0.0-canary.1405.6438.0
  yarn add @kickstartds/form@3.0.0-canary.1405.6438.0
  yarn add @kickstartds/bundler@3.0.0-canary.1405.6438.0
  yarn add @kickstartds/style-dictionary@3.0.0-canary.1405.6438.0
  ```
</details>

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0-next.11`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-next.11), [`@kickstartds/blog@3.0.0-next.10`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-next.10), [`@kickstartds/form@3.0.0-next.10`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-next.10) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0), [`@kickstartds/blog@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0), [`@kickstartds/bundler@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0), [`@kickstartds/core@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0), [`@kickstartds/form@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0), [`@kickstartds/style-dictionary@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%403.0.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Pull request merged**
