### PR TITLE
Style dictionary improvements

### LINKED ISSUE #1610: Style Dictionary blindspots
## Issues:

When implementing designs using the style dictionary, certain limitations were encountered, specifically in applying styles to:

- Distinct `text-color` for Headline and Copy
- `background-color` for bold elements
- Semantic token for `color-secondary`

These issues stem from systematic limitations:

- Branding Initialization Limitations: The semantic token layer is lacking important categories (one example would be the afformentioned copy/headline text-color)
- Inflexibility in Semantic Token Generation: The initial setup allows only for the addition of color scales without further semantic differentiation (e.g., `background-color`, `text-color`). A manually added `color-secondary` cannot have a semantic `background-color` token associated with it. 

Furthermore there are some questionable default values in the the branding initialisation:
- `background-color` token  used in the seciton component (accent) should not be `alpha` values as they might mix with the browser background, creating unpredictable outcomes
- there shouldnt be any `transparent` values unless the semantic token describes it as such (currently `background-color-interface-interactive`)

## TODOS:

- [x] ALL color token get a semantic token set (border-color, background-color, text-color)
- [x] ALL semantic color token get the same sub-categories (interactive > active, selected etc..)
- [x] remove visited token under text-color
- [x] add copy & display text-color token, they will only have semantic text-color token

```
text-color-copy: var(--ks-color-fg-alpha-3)
text-color-copy-interactive: var(--ks-link-color)
text-color-copy-interactive-hover: var(--ks-color-link-to-fg-2)
text-color-copy-interactive-active: var(--ks-color-link-to-fg-3)
text-color-copy-interactive-selected: var(--ks-color-link-to-fg-3)
```

```
text-color-display: var(--ks-color-fg)
text-color-display-interactive: var(--ks-color-link)
text-color-display-interactive-hover: var(--ks-color-link-to-fg-2)
text-color-display-interactive-active: var(--ks-color-link-to-fg-3)
text-color-display-interactive-selected: var(--ks-color-link-to-fg-3)
```

- [x] replace `alpha` with `to-bg` in background-color-accent & -bold
- [x] change the default value of background-color-interface-interactive to var(--ks-color-fg-alpha-8)
- [x] Add `to-fg` scale to color token
- [x] change the init prompts to the following:

```
"background": "#06081F",
"background-inverted": "#f1f1f3",
"foreground": "#fff",
"foreground-inverted": "#06081F",
```

- [x] adjust box-shadow token as referenced in comment
- [x] add semantic category `card` (`text-color`, `background-color`, `border-color`)

### PR DESCRIPTION
**Pull request by lmestel**
Resolves #1610

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/base@2.3.0-canary.1615.6674.0
  npm install @kickstartds/blog@2.3.0-canary.1615.6674.0
  npm install @kickstartds/core@2.3.0-canary.1615.6674.0
  npm install @kickstartds/form@2.3.0-canary.1615.6674.0
  npm install @kickstartds/style-dictionary@2.3.0-canary.1615.6674.0
  # or 
  yarn add @kickstartds/base@2.3.0-canary.1615.6674.0
  yarn add @kickstartds/blog@2.3.0-canary.1615.6674.0
  yarn add @kickstartds/core@2.3.0-canary.1615.6674.0
  yarn add @kickstartds/form@2.3.0-canary.1615.6674.0
  yarn add @kickstartds/style-dictionary@2.3.0-canary.1615.6674.0
  ```
</details>

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0), [`@kickstartds/blog@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0), [`@kickstartds/bundler@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0), [`@kickstartds/core@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0), [`@kickstartds/form@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0), [`@kickstartds/style-dictionary@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%403.0.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.0), [`@kickstartds/blog@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.0), [`@kickstartds/bundler@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.0), [`@kickstartds/core@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.0), [`@kickstartds/form@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Pull request merged**
