### PR TITLE
Revert translucent color token

### PR DESCRIPTION
**Pull request by lmestel**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/base@4.0.4-canary.1648.6891.0
  npm install @kickstartds/blog@4.0.4-canary.1648.6891.0
  npm install @kickstartds/core@4.0.4-canary.1648.6891.0
  npm install @kickstartds/form@4.0.4-canary.1648.6891.0
  npm install @kickstartds/bundler@4.0.4-canary.1648.6891.0
  npm install @kickstartds/style-dictionary@4.0.3-canary.1648.6891.0
  # or 
  yarn add @kickstartds/base@4.0.4-canary.1648.6891.0
  yarn add @kickstartds/blog@4.0.4-canary.1648.6891.0
  yarn add @kickstartds/core@4.0.4-canary.1648.6891.0
  yarn add @kickstartds/form@4.0.4-canary.1648.6891.0
  yarn add @kickstartds/bundler@4.0.4-canary.1648.6891.0
  yarn add @kickstartds/style-dictionary@4.0.3-canary.1648.6891.0
  ```
</details>

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.4-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.4-next.0), [`@kickstartds/blog@4.0.4-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.4-next.0), [`@kickstartds/bundler@4.0.4-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.4-next.0), [`@kickstartds/core@4.0.4-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.4-next.0), [`@kickstartds/form@4.0.4-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.4-next.0), [`@kickstartds/style-dictionary@4.0.3-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%404.0.3-next.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.4), [`@kickstartds/blog@4.0.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.4), [`@kickstartds/bundler@4.0.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.4), [`@kickstartds/core@4.0.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.4), [`@kickstartds/form@4.0.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.4), [`@kickstartds/style-dictionary@4.0.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%404.0.3) :rocket:

**Pull request merged**
