### PR TITLE
Simplify Collapsible Box Transition

### LINKED ISSUE #1311: Animate collapsible boxes with CSS
We can simplify the collapsible box by replacing most of the JS with CSS.

https://keithjgrant.com/posts/2023/04/transitioning-to-height-auto/

### PR DESCRIPTION
**Pull request by lmestel**
The collapsilbe box open-/close-animation is now a single CSS transition. This replaces the former Javascript animation logic (clone element, calculate target height, destroy cloned element, increase element height until target height is reached).

This resolves #1311

## Breaking Changes

- Changed Collapsible Box markup
- Removed utility functions `slideDown`, `slideUp`, `slideToggle` from `@kickstartds/core/lib/utils`
- Removed radio channel `core.window.hashchange`

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/base@3.0.0-canary.1387.6499.0
  npm install @kickstartds/blog@3.0.0-canary.1387.6499.0
  npm install @kickstartds/core@3.0.0-canary.1387.6499.0
  npm install @kickstartds/form@3.0.0-canary.1387.6499.0
  npm install @kickstartds/bundler@3.0.0-canary.1387.6499.0
  # or 
  yarn add @kickstartds/base@3.0.0-canary.1387.6499.0
  yarn add @kickstartds/blog@3.0.0-canary.1387.6499.0
  yarn add @kickstartds/core@3.0.0-canary.1387.6499.0
  yarn add @kickstartds/form@3.0.0-canary.1387.6499.0
  yarn add @kickstartds/bundler@3.0.0-canary.1387.6499.0
  ```
</details>

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-beta.0), [`@kickstartds/blog@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-beta.0), [`@kickstartds/bundler@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0-beta.0), [`@kickstartds/core@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0-beta.0), [`@kickstartds/form@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0), [`@kickstartds/blog@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0), [`@kickstartds/bundler@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0), [`@kickstartds/core@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0), [`@kickstartds/form@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0), [`@kickstartds/style-dictionary@3.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%403.0.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.0), [`@kickstartds/blog@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.0), [`@kickstartds/bundler@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.0), [`@kickstartds/core@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.0), [`@kickstartds/form@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Pull request merged**
