### PR TITLE
Add section mode `slider`

### LINKED ISSUE #1500: Add `slider` mode to `Section` component
Currently our `Section` allows `default`, `tile`, and `list` for its `mode` prop. We need a new `mode` called `slider` enabling sliding cards of components, like here for encore.de (https://www.encore.de/):
image

It will also need some basic properties (like enable / disable buttons, position of buttons, etc), and should ideally be compatible with all existing components.

### PR DESCRIPTION
**Pull request by lmestel**
The Section with mode `slider` renders its children in a scrollable single-row grid.

## New Props

- `sliderNavPosition`: (default `"below-center"`)
  - `"below-center"`: nav buttons are placed below the content, centered
  - `"below-endge"`: nav buttons are placed below the content, left and right at the section boundary
  - `"overlay"`: nav buttons fly over the content, left and right at the section boundary
- `sliderBackIcon`:  identifier for the back button icon (default `"arrow-left"`)
- `renderSliderBackIcon`: custom render function to replace the back button icon
- `sliderBackLabel`: `aria-label` for the back button (default `"Back"`)
- `sliderForwardIcon`: identifier for the forward button icon (default `"arrow-right"`)
- `renderSliderBackIcon`: custom render function to replace the forward button icon
- `sliderForwardLabel`: `aria-label` for the back button (default `"Forward"`)

## New Component Tokens

- `--l-section_slider-arrow--size` (default `2.5rem`)
- `--l-section_slider-arrow--padding` (default `var(--ks-spacing-xs)`)
- `--l-section_slider-arrow--color` (default `var(--ks-color-primary)`)
- `--l-section_slider-arrow--background`(default `var(--ks-background-color-interface-interactive)`)
- `--l-section_slider-arrow--opacity` (default `0.6`)
- `--l-section_slider-arrow--opacity-disabled` (default `0.3`)
- `--l-section_slider-arrow--opacity-hover` (default `0.9`)

Resolves #1500

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @kickstartds/base@2.3.0-canary.1550.6578.0
  npm install @kickstartds/blog@2.3.0-canary.1550.6578.0
  npm install @kickstartds/form@2.3.0-canary.1550.6578.0
  # or 
  yarn add @kickstartds/base@2.3.0-canary.1550.6578.0
  yarn add @kickstartds/blog@2.3.0-canary.1550.6578.0
  yarn add @kickstartds/form@2.3.0-canary.1550.6578.0
  ```
</details>

### CODE REVIEW

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.0), [`@kickstartds/blog@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.0), [`@kickstartds/form@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@2.3.0-beta.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.1), [`@kickstartds/blog@2.3.0-beta.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.1), [`@kickstartds/form@2.3.0-beta.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.1) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.2), [`@kickstartds/blog@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.2), [`@kickstartds/core@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%402.3.0-beta.0), [`@kickstartds/form@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.2), [`@kickstartds/style-dictionary@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%402.3.0-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: PR was released in [`@kickstartds/base@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.0), [`@kickstartds/blog@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.0), [`@kickstartds/bundler@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.0), [`@kickstartds/core@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.0), [`@kickstartds/form@4.0.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.0) :rocket:

**Comment by lmestel** [comment]
:rocket: PR was released in  :rocket:

**Pull request merged**
